server:
  port: 8888
spring:
  application:
    name: shop
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lih2ZbdMQiXXwsoU
            client-secret: 21673718490e74878eabe0ac20d95c94cff3d0ea
            scope: user

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

    show-sql: true
